/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiError {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "status")]
    pub status: u32,
}

impl ApiError {
    pub fn new(message: String, status: u32) -> ApiError {
        ApiError { message, status }
    }
}
