/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppEventOneOf8 {
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(
        rename = "target",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub target: Option<Option<Box<models::LlmTarget>>>,
}

impl AppEventOneOf8 {
    pub fn new(event: Event) -> AppEventOneOf8 {
        AppEventOneOf8 {
            event,
            target: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "llmFailed")]
    LlmFailed,
}

impl Default for Event {
    fn default() -> Event {
        Self::LlmFailed
    }
}
