/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportProjectRequest {
    #[serde(rename = "format")]
    pub format: models::ExportFormat,
    /// Multi-file export output. Defaults to folder-save transport.
    #[serde(rename = "output", skip_serializing_if = "Option::is_none")]
    pub output: Option<models::ExportOutput>,
    /// Optional subset of pages; defaults to every page.
    #[serde(
        rename = "pages",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pages: Option<Option<Vec<uuid::Uuid>>>,
}

impl ExportProjectRequest {
    pub fn new(format: models::ExportFormat) -> ExportProjectRequest {
        ExportProjectRequest {
            format,
            output: None,
            pages: None,
        }
    }
}
