/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobLogEvent : Diagnostic log line emitted during a pipeline run. Used for per-step and per-page status messages (skipped, ran, completion-decision) that don't rise to the level of `JobWarning`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobLogEvent {
    #[serde(
        rename = "detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub detail: Option<Option<String>>,
    #[serde(rename = "jobId")]
    pub job_id: String,
    #[serde(rename = "level")]
    pub level: models::JobLogLevel,
    #[serde(rename = "message")]
    pub message: String,
    /// 0-based page index this log refers to. `None` for global messages.
    #[serde(
        rename = "pageIndex",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub page_index: Option<Option<u32>>,
    /// Engine id (e.g. `\"paddle-ocr\"`) when applicable.
    #[serde(
        rename = "stepId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub step_id: Option<Option<String>>,
    #[serde(rename = "totalPages")]
    pub total_pages: u32,
}

impl JobLogEvent {
    /// Diagnostic log line emitted during a pipeline run. Used for per-step and per-page status messages (skipped, ran, completion-decision) that don't rise to the level of `JobWarning`.
    pub fn new(
        job_id: String,
        level: models::JobLogLevel,
        message: String,
        total_pages: u32,
    ) -> JobLogEvent {
        JobLogEvent {
            detail: None,
            job_id,
            level,
            message,
            page_index: None,
            step_id: None,
            total_pages,
        }
    }
}
