/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Page {
    /// Whether this page is considered fully processed / ready for export. Auto-set by the pipeline when a page finishes all steps (or has no text to process). Can also be toggled manually by the user.
    #[serde(rename = "completed", skip_serializing_if = "Option::is_none")]
    pub completed: Option<bool>,
    #[serde(rename = "height")]
    pub height: u32,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    /// Stacking = insertion order. Bottom-first: `source` is typically first, `rendered` typically last.
    #[serde(rename = "nodes")]
    pub nodes: std::collections::HashMap<String, models::Node>,
    #[serde(rename = "width")]
    pub width: u32,
}

impl Page {
    pub fn new(
        height: u32,
        id: uuid::Uuid,
        name: String,
        nodes: std::collections::HashMap<String, models::Node>,
        width: u32,
    ) -> Page {
        Page {
            completed: None,
            height,
            id,
            name,
            nodes,
            width,
        }
    }
}
