/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineParallelismConfig {
    #[serde(rename = "max_active_steps", skip_serializing_if = "Option::is_none")]
    pub max_active_steps: Option<u32>,
    #[serde(rename = "max_llm_steps", skip_serializing_if = "Option::is_none")]
    pub max_llm_steps: Option<u32>,
    #[serde(rename = "max_model_steps", skip_serializing_if = "Option::is_none")]
    pub max_model_steps: Option<u32>,
    #[serde(
        rename = "max_pages_in_flight",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_pages_in_flight: Option<u32>,
    #[serde(rename = "max_render_steps", skip_serializing_if = "Option::is_none")]
    pub max_render_steps: Option<u32>,
    #[serde(
        rename = "max_same_engine_steps",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_same_engine_steps: Option<u32>,
}

impl PipelineParallelismConfig {
    pub fn new() -> PipelineParallelismConfig {
        PipelineParallelismConfig {
            max_active_steps: None,
            max_llm_steps: None,
            max_model_steps: None,
            max_pages_in_flight: None,
            max_render_steps: None,
            max_same_engine_steps: None,
        }
    }
}
