/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineParallelismConfigPatch {
    #[serde(
        rename = "maxActiveSteps",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_active_steps: Option<Option<u32>>,
    #[serde(
        rename = "maxLlmSteps",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_llm_steps: Option<Option<u32>>,
    #[serde(
        rename = "maxModelSteps",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_model_steps: Option<Option<u32>>,
    #[serde(
        rename = "maxPagesInFlight",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_pages_in_flight: Option<Option<u32>>,
    #[serde(
        rename = "maxRenderSteps",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_render_steps: Option<Option<u32>>,
    #[serde(
        rename = "maxSameEngineSteps",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_same_engine_steps: Option<Option<u32>>,
}

impl PipelineParallelismConfigPatch {
    pub fn new() -> PipelineParallelismConfigPatch {
        PipelineParallelismConfigPatch {
            max_active_steps: None,
            max_llm_steps: None,
            max_model_steps: None,
            max_pages_in_flight: None,
            max_render_steps: None,
            max_same_engine_steps: None,
        }
    }
}
