/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiError,
  UnloadEngineParams
} from '../schemas';

import { fetchApi } from '.././fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getUnloadEngineUrl = (params: UnloadEngineParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/engines/cache?${stringifiedParams}` : `/api/v1/engines/cache`
}

export const unloadEngine = async (params: UnloadEngineParams, options?: RequestInit): Promise<void> => {

  return fetchApi<void>(getUnloadEngineUrl(params),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getUnloadEngineMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unloadEngine>>, TError,{params: UnloadEngineParams}, TContext>, request?: SecondParameter<typeof fetchApi>}
): UseMutationOptions<Awaited<ReturnType<typeof unloadEngine>>, TError,{params: UnloadEngineParams}, TContext> => {

const mutationKey = ['unloadEngine'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unloadEngine>>, {params: UnloadEngineParams}> = (props) => {
          const {params} = props ?? {};

          return  unloadEngine(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UnloadEngineMutationResult = NonNullable<Awaited<ReturnType<typeof unloadEngine>>>

    export type UnloadEngineMutationError = ApiError

    export const useUnloadEngine = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unloadEngine>>, TError,{params: UnloadEngineParams}, TContext>, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unloadEngine>>,
        TError,
        {params: UnloadEngineParams},
        TContext
      > => {
      return useMutation(getUnloadEngineMutationOptions(options), queryClient);
    }
