/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { BootstrapPhase } from './bootstrapPhase'

export interface BootstrapStatus {
  /** @nullable */
  error?: string | null
  phase: BootstrapPhase
}
