/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type ExportOutput = typeof ExportOutput[keyof typeof ExportOutput];


export const ExportOutput = {
  folder: 'folder',
  zip: 'zip',
} as const;
