/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

/**
 * Severity for diagnostic pipeline logs (`JobLogEvent`).
 */
export type JobLogLevel = typeof JobLogLevel[keyof typeof JobLogLevel];


export const JobLogLevel = {
  info: 'info',
  warn: 'warn',
  error: 'error',
} as const;
