/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface PipelineParallelismConfig {
  /** @minimum 0 */
  max_active_steps?: number;
  /** @minimum 0 */
  max_llm_steps?: number;
  /** @minimum 0 */
  max_model_steps?: number;
  /** @minimum 0 */
  max_pages_in_flight?: number;
  /** @minimum 0 */
  max_render_steps?: number;
  /** @minimum 0 */
  max_same_engine_steps?: number;
}
