/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { PipelineParallelismConfigPatchEngineLimits } from './pipelineParallelismConfigPatchEngineLimits';

export interface PipelineParallelismConfigPatch {
  /** @nullable */
  engineLimits?: PipelineParallelismConfigPatchEngineLimits;
  /**
     * @minimum 0
     * @nullable
     */
  maxActiveSteps?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  maxLlmSteps?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  maxModelSteps?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  maxPagesInFlight?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  maxRenderSteps?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  maxSameEngineSteps?: number | null;
}
