/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { PipelineParallelismConfigPatch } from './pipelineParallelismConfigPatch';

export interface PipelineConfigPatch {
  /** @nullable */
  bubbleSegmenter?: string | null;
  /** @nullable */
  detector?: string | null;
  /** @nullable */
  fontDetector?: string | null;
  /** @nullable */
  inpainter?: string | null;
  /** @nullable */
  ocr?: string | null;
  parallelism?: null | PipelineParallelismConfigPatch;
  /** @nullable */
  renderer?: string | null;
  /** @nullable */
  segmenter?: string | null;
  /** @nullable */
  translator?: string | null;
}
